# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: txlog
    binary: txlog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      -trimpath
    ldflags:
      - -s -w -extldflags=-static

nfpms:
  - id: txlog
    package_name: txlog
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Rodrigo de Avila
    homepage: https://txlog.rda.run
    maintainer: Rodrigo de Avila <me@rdeavila>
    description: |
      The Transaction Log project aims to track package history on RPM systems,
      compiling data on the number of updates and installs. Designed to enhance
      system reliability, this initiative collects and centralizes information,
      providing valuable insights into the evolution of packages.

      This package contains the Agent, which compiles transactional data and sends
      it to a central server, enabling real-time monitoring and analytics. By
      aggregating and processing package history, the Agent provides actionable
      insights for system administrators to optimize their RPM-based
    license: MIT
    epoch: 0
    release: 1
    section: default
    priority: extra
    contents:
      - src: ./doc/txlog.1.gz
        dst: /usr/share/man/man1/txlog.1.gz
      - src: ./conf/txlog.yaml
        dst: /etc/txlog.yaml
        type: config|noreplace
      - src: ./bin/txlog
        dst: /usr/bin/txlog

# archives:
#   - formats: [tar.gz]
#     # this name template makes the OS and Arch compatible with the results of `uname`.
#     name_template: >-
#       {{ .ProjectName }}_
#       {{- title .Os }}_
#       {{- if eq .Arch "amd64" }}x86_64
#       {{- else if eq .Arch "386" }}i386
#       {{- else }}{{ .Arch }}{{ end }}
#       {{- if .Arm }}v{{ .Arm }}{{ end }}
#     # use zip for windows archives
#     format_overrides:
#       - goos: windows
#         formats: [zip]

# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - "^docs:"
#       - "^test:"

# release:
#   footer: >-

#     ---

#     Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
